version: '3'

services:
  wordpress:
    container_name: wordpress
    # dependency will launch targeted services first (in this case is mariaDb)
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
      
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    # volumes are independent file system used for persistent data storage across multiple containers 
    volumes:
    # data is in html type
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    # in case of problem we restart automatically the container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      # must be in home/zwong/data @ iMac
      device: /home/zwong/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      # must be in home/zwong/data @ iMac
      device: /home/zwong/data/mysql
      o: bind

networks:
  network:
    driver: bridge
